/**
 * DANFE PDF Viewer Component
 * 
 * Simplified PDF viewer component that only loads PDFs from URLs
 * Uses files generated by DANFEGenerator.ts via backend routes
 */

import React, { useCallback, useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';

// Import CSS files with proper paths
import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';

// Import PDF worker configuration (configured globally in App.tsx)
import { getPdfWorkerSource, isPdfWorkerConfigured } from '../utils/pdfWorkerConfig';

// Add CSS debugging
console.log('[DANFEPDFViewer] CSS files imported for react-pdf');

export interface DANFEPDFViewerProps {
  pdfUrl: string; // URL to PDF file served by backend
  onLoadSuccess?: (pdf: any) => void;
  onLoadError?: (error: Error) => void;
  className?: string;
}

export const DANFEPDFViewer: React.FC<DANFEPDFViewerProps> = ({
  pdfUrl,
  onLoadSuccess,
  onLoadError,
  className = ''
}) => {
  const [numPages, setNumPages] = useState<number>(0);
  const [pageNumber, setPageNumber] = useState<number>(1);
  const [scale, setScale] = useState<number>(1.0);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [loadingTimeout, setLoadingTimeout] = useState<NodeJS.Timeout | null>(null);
  const [currentPdfSource, setCurrentPdfSource] = useState<string | object | null>(null);
  const [loadingMethod, setLoadingMethod] = useState<'url' | 'blob'>('url');

  // Component mounted - worker configured globally
  React.useEffect(() => {
    console.log('[DANFEPDFViewer] Component mounted');
    console.log('  - PDF worker configured:', isPdfWorkerConfigured());
    console.log('  - PDF worker source:', getPdfWorkerSource());
    console.log('  - PDF.js version:', pdfjs.version);
    console.log('  - PDF URL:', pdfUrl);
    console.log('  - GlobalWorkerOptions.workerSrc:', pdfjs.GlobalWorkerOptions.workerSrc);
  }, [pdfUrl]);

  // Set up loading timeout
  React.useEffect(() => {
    if (isLoading && !error) {
      console.log('[DANFEPDFViewer] Setting up loading timeout (30 seconds)');
      const timeout = setTimeout(() => {
        console.error('[DANFEPDFViewer] Loading timeout - PDF failed to load within 30 seconds');
        setIsLoading(false);
        setError('Tempo limite excedido ao carregar PDF');
        if (onLoadError) {
          onLoadError(new Error('PDF loading timeout'));
        }
      }, 30000); // 30 second timeout for URL loading

      setLoadingTimeout(timeout);

      return () => {
        if (timeout) {
          clearTimeout(timeout);
        }
      };
    }
  }, [isLoading, error, onLoadError]);

  // Clear timeout when loading stops
  React.useEffect(() => {
    if (!isLoading && loadingTimeout) {
      console.log('[DANFEPDFViewer] Clearing loading timeout');
      clearTimeout(loadingTimeout);
      setLoadingTimeout(null);
    }
  }, [isLoading, loadingTimeout]);

  // Reset state when URL changes
  React.useEffect(() => {
    if (pdfUrl) {
      console.log('[DANFEPDFViewer] PDF URL changed, resetting state');
      setIsLoading(true);
      setError(null);
      setNumPages(0);
      setPageNumber(1);
      setCurrentPdfSource(null); // Reset to use original URL
      setLoadingMethod('url'); // Start with URL method
    }
  }, [pdfUrl]);

  const onDocumentLoadSuccess = useCallback((pdf: any) => {
    console.log('[DANFEPDFViewer] PDF document loaded successfully:', pdf);
    console.log('[DANFEPDFViewer] PDF info:', {
      numPages: pdf.numPages
    });
    setNumPages(pdf.numPages);
    setPageNumber(1);
    setIsLoading(false);
    setError(null);
    
    // Clear timeout
    if (loadingTimeout) {
      console.log('[DANFEPDFViewer] Clearing loading timeout on success');
      clearTimeout(loadingTimeout);
      setLoadingTimeout(null);
    }
    
    console.log(`[DANFEPDFViewer] PDF loaded successfully: ${pdf.numPages} pages`);
    
    if (onLoadSuccess) {
      onLoadSuccess(pdf);
    }
  }, [onLoadSuccess, loadingTimeout]);

  const onDocumentLoadError = useCallback(async (error: Error) => {
    console.error('[DANFEPDFViewer] PDF document load error:', error);
    console.error('[DANFEPDFViewer] Error details:', {
      name: error.name,
      message: error.message,
      stack: error.stack
    });
    console.error('[DANFEPDFViewer] PDF URL that failed:', pdfUrl);
    console.error('[DANFEPDFViewer] Loading method:', loadingMethod);
    
    // Clear timeout
    if (loadingTimeout) {
      clearTimeout(loadingTimeout);
      setLoadingTimeout(null);
    }
    
    // If URL method failed, try blob method automatically
    if (loadingMethod === 'url') {
      console.log('[DANFEPDFViewer] URL method failed, trying blob method...');
      
      try {
        setLoadingMethod('blob');
        setIsLoading(true);
        setError(null);
        
        const authToken = localStorage.getItem('revio_auth_token');
        const response = await fetch(pdfUrl, {
          headers: authToken ? {
            'Authorization': `Bearer ${authToken}`
          } : {}
        });
        
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        
        const blob = await response.blob();
        console.log('[DANFEPDFViewer] Blob loaded successfully, size:', blob.size);
        
        // Create blob URL and set as new source
        const blobUrl = URL.createObjectURL(blob);
        console.log('[DANFEPDFViewer] Blob URL created:', blobUrl);
        
        setCurrentPdfSource(blobUrl);
        
        // Don't call onLoadError yet, let the blob method try first
        return;
        
      } catch (blobError: any) {
        console.error('[DANFEPDFViewer] Blob method also failed:', blobError);
        // Fall through to normal error handling
      }
    }
    
    setIsLoading(false);
    
    // Set user-friendly error message
    let errorMessage = 'Erro ao carregar PDF';
    if (error.message.includes('404') || error.message.includes('Not Found')) {
      errorMessage = 'PDF não encontrado no servidor';
    } else if (error.message.includes('401') || error.message.includes('Unauthorized')) {
      errorMessage = 'Não autorizado a acessar este PDF';
    } else if (error.message.includes('timeout')) {
      errorMessage = 'Tempo limite excedido ao carregar PDF';
    } else if (error.message.includes('network') || error.message.includes('fetch')) {
      errorMessage = 'Erro de conexão ao carregar PDF';
    }
    
    if (loadingMethod === 'blob') {
      errorMessage += ' (tentativa com blob também falhou)';
    }
    
    console.error('[DANFEPDFViewer] Final error message:', errorMessage);
    setError(errorMessage);
    
    if (onLoadError) {
      onLoadError(error);
    }
  }, [onLoadError, loadingTimeout, pdfUrl, loadingMethod]);

  // Navigation functions
  const goToPrevPage = useCallback(() => {
    setPageNumber(prev => Math.max(1, prev - 1));
  }, []);

  const goToNextPage = useCallback(() => {
    setPageNumber(prev => Math.min(numPages, prev + 1));
  }, [numPages]);

  const goToFirstPage = useCallback(() => {
    setPageNumber(1);
  }, []);

  const goToLastPage = useCallback(() => {
    setPageNumber(numPages);
  }, [numPages]);

  // Zoom functions
  const zoomIn = useCallback(() => {
    setScale(prev => Math.min(3.0, prev + 0.25));
  }, []);

  const zoomOut = useCallback(() => {
    setScale(prev => Math.max(0.5, prev - 0.25));
  }, []);

  const resetZoom = useCallback(() => {
    setScale(1.0);
  }, []);

  // Prepare PDF source with authentication
  const pdfSource = React.useMemo(() => {
    // Use currentPdfSource if available (blob URL), otherwise use original pdfUrl
    const sourceUrl = currentPdfSource || pdfUrl;
    
    if (!sourceUrl) {
      return null;
    }

    console.log('[DANFEPDFViewer] Preparing PDF source for URL:', sourceUrl);
    console.log('[DANFEPDFViewer] Loading method:', loadingMethod);

    // If it's a blob URL, use it directly
    if (typeof sourceUrl === 'string' && sourceUrl.startsWith('blob:')) {
      console.log('[DANFEPDFViewer] Using blob URL directly:', sourceUrl);
      return sourceUrl;
    }

    // Add authentication token to headers if available and it's not a blob URL
    const authToken = localStorage.getItem('revio_auth_token');
    console.log('[DANFEPDFViewer] Auth token available:', !!authToken);
    
    if (authToken && typeof sourceUrl === 'string') {
      const source = {
        url: sourceUrl,
        httpHeaders: {
          'Authorization': `Bearer ${authToken}`
        },
        withCredentials: false
      };
      console.log('[DANFEPDFViewer] Using authenticated PDF source:', source);
      return source;
    }

    // Fallback to simple URL
    console.log('[DANFEPDFViewer] Using simple URL (no auth):', sourceUrl);
    return sourceUrl;
  }, [pdfUrl, currentPdfSource, loadingMethod]);

  // Test the PDF URL directly when component mounts
  React.useEffect(() => {
    if (pdfUrl && pdfSource) {
      console.log('[DANFEPDFViewer] Testing PDF URL accessibility...');
      
      const authToken = localStorage.getItem('revio_auth_token');
      const headers: Record<string, string> = {};
      
      if (authToken) {
        headers['Authorization'] = `Bearer ${authToken}`;
      }
      
      fetch(pdfUrl, {
        method: 'HEAD',
        headers
      })
      .then(response => {
        console.log('[DANFEPDFViewer] PDF URL test result:', {
          status: response.status,
          statusText: response.statusText,
          ok: response.ok,
          contentType: response.headers.get('content-type'),
          contentLength: response.headers.get('content-length')
        });
        
        if (!response.ok) {
          console.error('[DANFEPDFViewer] PDF URL is not accessible:', response.status, response.statusText);
        }
      })
      .catch(error => {
        console.error('[DANFEPDFViewer] PDF URL test failed:', error);
      });
    }
  }, [pdfUrl, pdfSource]);

  console.log('[DANFEPDFViewer] Render - pdfSource:', {
    hasPdfSource: !!pdfSource,
    pdfUrl: pdfUrl,
    isLoading,
    hasError: !!error
  });

  if (!pdfUrl) {
    console.log('[DANFEPDFViewer] No PDF URL provided');
    return (
      <div className={`flex items-center justify-center h-full bg-gray-100 ${className}`}>
        <div className="text-center">
          <div className="text-gray-400 text-4xl mb-2">📄</div>
          <p className="text-gray-600">Nenhum PDF para exibir</p>
        </div>
      </div>
    );
  }

  console.log('[DANFEPDFViewer] Rendering PDF viewer component');

  return (
    <div className={`flex flex-col h-full bg-gray-100 ${className}`}>
      {/* Toolbar */}
      <div className="bg-white border-b border-gray-300 px-4 py-2 flex items-center justify-between">
        <div className="flex items-center space-x-2">
          {/* Navigation Controls */}
          <button
            onClick={goToFirstPage}
            disabled={pageNumber <= 1}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 disabled:bg-gray-100 disabled:text-gray-400 rounded"
            title="Primeira página"
          >
            ⏮
          </button>
          <button
            onClick={goToPrevPage}
            disabled={pageNumber <= 1}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 disabled:bg-gray-100 disabled:text-gray-400 rounded"
            title="Página anterior"
          >
            ◀
          </button>
          <span className="text-sm text-gray-600 min-w-[80px] text-center">
            {!isLoading && !error ? `${pageNumber} / ${numPages}` : '-'}
          </span>
          <button
            onClick={goToNextPage}
            disabled={pageNumber >= numPages}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 disabled:bg-gray-100 disabled:text-gray-400 rounded"
            title="Próxima página"
          >
            ▶
          </button>
          <button
            onClick={goToLastPage}
            disabled={pageNumber >= numPages}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 disabled:bg-gray-100 disabled:text-gray-400 rounded"
            title="Última página"
          >
            ⏭
          </button>
        </div>

        <div className="flex items-center space-x-2">
          {/* Zoom Controls */}
          <button
            onClick={zoomOut}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 rounded"
            title="Diminuir zoom"
          >
            🔍-
          </button>
          <span className="text-sm text-gray-600 min-w-[60px] text-center">
            {Math.round(scale * 100)}%
          </span>
          <button
            onClick={zoomIn}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 rounded"
            title="Aumentar zoom"
          >
            🔍+
          </button>
          <button
            onClick={resetZoom}
            className="px-2 py-1 text-sm bg-gray-200 hover:bg-gray-300 rounded"
            title="Zoom 100%"
          >
            100%
          </button>
        </div>
      </div>

      {/* PDF Content Area */}
      <div className="flex-1 overflow-auto bg-gray-200 p-4">
        {/* Loading State */}
        {isLoading && (
          <div className="flex items-center justify-center h-full">
            <div className="text-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500 mx-auto mb-2"></div>
              <p className="text-gray-600">Carregando PDF...</p>
            </div>
          </div>
        )}

        {/* Error State */}
        {error && (
          <div className="flex items-center justify-center h-full">
            <div className="text-center">
              <div className="text-red-500 text-lg mb-2">❌</div>
              <p className="text-gray-600">{error}</p>
            </div>
          </div>
        )}

        {/* PDF Viewer */}
        {!isLoading && !error && (
          <div className="flex justify-center">
            <Document
              file={pdfSource as any} // Type assertion for flexibility
              onLoadSuccess={onDocumentLoadSuccess}
              onLoadError={onDocumentLoadError}
              onLoadProgress={(progress) => {
                console.log('[DANFEPDFViewer] Document load progress:', progress);
              }}
              onSourceSuccess={() => {
                console.log('[DANFEPDFViewer] Document source loaded successfully');
              }}
              onSourceError={(error) => {
                console.error('[DANFEPDFViewer] Document source error:', error);
                console.error('[DANFEPDFViewer] Source error details:', {
                  name: error.name,
                  message: error.message,
                  stack: error.stack
                });
                console.error('[DANFEPDFViewer] PDF source that failed:', pdfSource);
              }}
              options={{
                // Configurações mínimas para melhor compatibilidade
                cMapUrl: `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/cmaps/`,
                cMapPacked: true,
                standardFontDataUrl: `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/standard_fonts/`,
                // Configurações de timeout mais permissivas
                httpHeaders: {},
                withCredentials: false,
                // Configurações de debug
                verbosity: 1,
                // Increase timeout
                maxImageSize: 1024 * 1024 * 10, // 10MB
                // Better error handling
                stopAtErrors: false
              }}
              loading={
                <div className="flex items-center justify-center h-64">
                  <div className="text-center">
                    <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500 mx-auto mb-2"></div>
                    <p className="text-gray-600">
                      {loadingMethod === 'url' ? 'Carregando documento...' : 'Carregando via blob...'}
                    </p>
                    <p className="text-xs text-gray-500 mt-2">
                      Método: {loadingMethod === 'url' ? 'URL direta' : 'Blob local'}
                    </p>
                    <p className="text-xs text-gray-500">
                      URL: {typeof pdfSource === 'string' ? pdfSource : (pdfSource as any)?.url || 'blob'}
                    </p>
                  </div>
                </div>
              }
              error={
                <div className="flex items-center justify-center h-64">
                  <div className="text-center">
                    <div className="text-red-500 text-lg mb-2">❌</div>
                    <p className="text-gray-600">Erro ao carregar PDF</p>
                    <p className="text-xs text-gray-500 mt-2">URL: {typeof pdfSource === 'string' ? pdfSource : (pdfSource as any).url}</p>
                  </div>
                </div>
              }
            >
              <Page
                pageNumber={pageNumber}
                scale={scale}
                loading={
                  <div className="flex items-center justify-center h-64 bg-white border">
                    <div className="text-center">
                      <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-blue-500 mx-auto mb-2"></div>
                      <p className="text-gray-600 text-sm">Carregando página...</p>
                    </div>
                  </div>
                }
                error={
                  <div className="flex items-center justify-center h-64 bg-white border">
                    <div className="text-center">
                      <div className="text-red-500 text-lg mb-2">❌</div>
                      <p className="text-gray-600 text-sm">Erro ao carregar página</p>
                    </div>
                  </div>
                }
                className="shadow-lg"
              />
            </Document>
          </div>
        )}
      </div>

      {/* Status Bar */}
      <div className="bg-white border-t border-gray-300 px-4 py-1 text-xs text-gray-500">
        {!isLoading && !error && (
          <span>
            Página {pageNumber} de {numPages} • Zoom {Math.round(scale * 100)}%
          </span>
        )}
      </div>
    </div>
  );
};

export default DANFEPDFViewer;