// Error Codes
export const ERROR_CODES = {
  // Authentication
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // DANFE
  DANFE_GENERATION_FAILED: 'DANFE_GENERATION_FAILED',
  XML_NOT_FOUND: 'XML_NOT_FOUND',
  PDF_GENERATION_ERROR: 'PDF_GENERATION_ERROR',
  
  // Network
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  
  // NFe Grouping
  GROUPING_CONFIG_ERROR: 'GROUPING_CONFIG_ERROR',
  NFE_PREFIX_ERROR: 'NFE_PREFIX_ERROR',
  QUERY_INTERCEPTION_ERROR: 'QUERY_INTERCEPTION_ERROR',
  ORDERING_CONFIG_ERROR: 'ORDERING_CONFIG_ERROR',
  
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND'
} as const;